{{- if or .Values.database.password .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- with .Values.database.password }}
  SPRING_DATASOURCE_USERNAME: {{ required "database.username must be set" $.Values.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
