-- Owned by announcements-service. Shape matches the table legacy-portal created in the
-- shared `announcements` schema (Hibernate 5, ddl-auto=update), so this is a no-op when the
-- service adopts an existing legacy database and a full create on a fresh one.
CREATE TABLE IF NOT EXISTS announcement (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200)  NOT NULL,
    body        VARCHAR(4000) NOT NULL,
    published   BOOLEAN       NOT NULL,
    created_at  TIMESTAMP(6)  NOT NULL
);

CREATE INDEX IF NOT EXISTS announcement_published_created_at_idx
    ON announcement (published, created_at DESC);
