-- Owned by feedback-service. Shape matches the table legacy-portal created in the shared
-- `feedback` schema (Hibernate 5, ddl-auto=update), so this is a no-op when the service
-- adopts an existing legacy database and a full create on a fresh one.
CREATE TABLE IF NOT EXISTS feedback (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     VARCHAR(100)  NOT NULL,
    rating      INTEGER       NOT NULL,
    message     VARCHAR(2000) NOT NULL,
    created_at  TIMESTAMP(6)  NOT NULL
);

CREATE INDEX IF NOT EXISTS feedback_user_id_created_at_idx
    ON feedback (user_id, created_at DESC);
